name: docker4640

on:
  push:
    branches:
      - 'master'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout the code
        uses: actions/checkout@v3
      
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          file: ./backend/Dockerfile
          push: true
          tags: raihankheraj/demo-backend-4640:latest
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          file: ./frontend/Dockerfile
          push: true
          tags: raihankheraj/demo-frontend-4640:latest